// Island Cone Games

#pragma once

#include "NativeGameplayTags.h"

namespace ConeWarriorGameplayTags
{
	/** Input Tags **/
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);

	/* Player Tags */
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	CONEWARRIORV2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);


}